// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Numera.Platform.Db;

#nullable disable

namespace Numera.Platform.Db.Migrations
{
    [DbContext(typeof(NumeraDbContext))]
    [Migration("20260728145309_RecurringInvoices")]
    partial class RecurringInvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Numera.Modules.Catalog.CatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<decimal?>("CostPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("cost_price");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_number");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("NetPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("net_price");

                    b.Property<string>("RevenueAccount")
                        .HasColumnType("text")
                        .HasColumnName("revenue_account");

                    b.Property<int>("TaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("tax_category");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<decimal?>("VatRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.HasKey("Id")
                        .HasName("pk_catalog_items");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_catalog_items_tenant_id_name");

                    b.ToTable("catalog_items");
                });

            modelBuilder.Entity("Numera.Modules.Crm.BusinessPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Bic")
                        .HasColumnType("text")
                        .HasColumnName("bic");

                    b.Property<string>("CreditorAccount")
                        .HasColumnType("text")
                        .HasColumnName("creditor_account");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("text")
                        .HasColumnName("customer_number");

                    b.Property<string>("DebtorAccount")
                        .HasColumnType("text")
                        .HasColumnName("debtor_account");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_currency");

                    b.Property<int?>("DefaultTaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("default_tax_category");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_customer");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("boolean")
                        .HasColumnName("is_supplier");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("LegalForm")
                        .HasColumnType("text")
                        .HasColumnName("legal_form");

                    b.Property<string>("LeitwegId")
                        .HasColumnType("text")
                        .HasColumnName("leitweg_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PaymentTermsNetDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_terms_net_days");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("SkontoDays")
                        .HasColumnType("integer")
                        .HasColumnName("skonto_days");

                    b.Property<decimal?>("SkontoPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("skonto_percent");

                    b.Property<string>("SupplierNumber")
                        .HasColumnType("text")
                        .HasColumnName("supplier_number");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VatId")
                        .HasColumnType("text")
                        .HasColumnName("vat_id");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_partners_tenant_id_name");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("Numera.Modules.Crm.PartnerActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .HasColumnType("text")
                        .HasColumnName("ref_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_partner_activities");

                    b.HasIndex("TenantId", "PartnerId", "OccurredAt")
                        .HasDatabaseName("ix_partner_activities_tenant_id_partner_id_occurred_at");

                    b.ToTable("partner_activities");
                });

            modelBuilder.Entity("Numera.Modules.Crm.PartnerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Salutation")
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_partner_contacts");

                    b.HasIndex("TenantId", "PartnerId")
                        .HasDatabaseName("ix_partner_contacts_tenant_id_partner_id");

                    b.ToTable("partner_contacts");
                });

            modelBuilder.Entity("Numera.Modules.Crm.PartnerNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_partner_notes");

                    b.HasIndex("TenantId", "PartnerId")
                        .HasDatabaseName("ix_partner_notes_tenant_id_partner_id");

                    b.ToTable("partner_notes");
                });

            modelBuilder.Entity("Numera.Modules.Ledger.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_accounts_tenant_id_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Numera.Modules.Ledger.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_journal_entries_tenant_id_id");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Numera.Modules.Ledger.Posting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_postings");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_postings_journal_entry_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_postings_tenant_id_id");

                    b.ToTable("postings", (string)null);
                });

            modelBuilder.Entity("Numera.Modules.Sales.CompanyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BankName")
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<string>("Bic")
                        .HasColumnType("text")
                        .HasColumnName("bic");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<int?>("DefaultPaymentTermsNetDays")
                        .HasColumnType("integer")
                        .HasColumnName("default_payment_terms_net_days");

                    b.Property<int?>("DefaultTaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("default_tax_category");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<bool>("IsKleinunternehmer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_kleinunternehmer");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("legal_name");

                    b.Property<byte[]>("LogoBytes")
                        .HasColumnType("bytea")
                        .HasColumnName("logo_bytes");

                    b.Property<string>("LogoContentType")
                        .HasColumnType("text")
                        .HasColumnName("logo_content_type");

                    b.Property<string>("LogoRef")
                        .HasColumnType("text")
                        .HasColumnName("logo_ref");

                    b.Property<string>("ManagingDirector")
                        .HasColumnType("text")
                        .HasColumnName("managing_director");

                    b.Property<string>("RegisterCourt")
                        .HasColumnType("text")
                        .HasColumnName("register_court");

                    b.Property<string>("RegisterNumber")
                        .HasColumnType("text")
                        .HasColumnName("register_number");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VatId")
                        .HasColumnType("text")
                        .HasColumnName("vat_id");

                    b.HasKey("Id")
                        .HasName("pk_company_profile");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_company_profile_tenant_id");

                    b.ToTable("company_profile");
                });

            modelBuilder.Entity("Numera.Modules.Sales.DocumentNumberFormat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DocType")
                        .HasColumnType("integer")
                        .HasColumnName("doc_type");

                    b.Property<bool>("IncludeYear")
                        .HasColumnType("boolean")
                        .HasColumnName("include_year");

                    b.Property<int>("Padding")
                        .HasColumnType("integer")
                        .HasColumnName("padding");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_document_number_formats");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_document_number_formats_tenant_id_id");

                    b.ToTable("document_number_formats");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Dunning.DunningLevelConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("ChargeInterest")
                        .HasColumnType("boolean")
                        .HasColumnName("charge_interest");

                    b.Property<int>("DaysAfterDue")
                        .HasColumnType("integer")
                        .HasColumnName("days_after_due");

                    b.Property<decimal>("Fee")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee");

                    b.Property<decimal>("InterestRatePercent")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)")
                        .HasColumnName("interest_rate_percent");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TemplateTextDe")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_text_de");

                    b.Property<string>("TemplateTextEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template_text_en");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_dunning_level_config");

                    b.HasIndex("TenantId", "Level")
                        .IsUnique()
                        .HasDatabaseName("ix_dunning_level_config_tenant_id_level");

                    b.ToTable("dunning_level_config");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Dunning.DunningNotice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal>("Fee")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("fee");

                    b.Property<decimal>("Interest")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("interest");

                    b.Property<decimal>("InterestRatePercent")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("interest_rate_percent");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateOnly>("NewDueDate")
                        .HasColumnType("date")
                        .HasColumnName("new_due_date");

                    b.Property<Guid>("OpenItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("open_item_id");

                    b.Property<decimal>("OverdueAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("overdue_amount");

                    b.Property<byte[]>("RenderedPdf")
                        .HasColumnType("bytea")
                        .HasColumnName("rendered_pdf");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalToPay")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_to_pay");

                    b.HasKey("Id")
                        .HasName("pk_dunning_notice");

                    b.HasIndex("TenantId", "OpenItemId")
                        .HasDatabaseName("ix_dunning_notice_tenant_id_open_item_id");

                    b.ToTable("dunning_notice");
                });

            modelBuilder.Entity("Numera.Modules.Sales.EInvoice.EInvoiceArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<int>("Format")
                        .HasColumnType("integer")
                        .HasColumnName("format");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("ValidationReport")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_report");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("validation_status");

                    b.Property<byte[]>("Xml")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("xml");

                    b.HasKey("Id")
                        .HasName("pk_document_einvoice");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_document_einvoice_tenant_id_document_id");

                    b.ToTable("document_einvoice");
                });

            modelBuilder.Entity("Numera.Modules.Sales.EInvoice.Inbound.InboundDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<string>("Currency")
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<int>("DetectedFormat")
                        .HasColumnType("integer")
                        .HasColumnName("detected_format");

                    b.Property<DateOnly?>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<Guid?>("MatchedPartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("matched_partner_id");

                    b.Property<byte[]>("OriginalBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("original_bytes");

                    b.Property<string>("OriginalContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_content_type");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_file_name");

                    b.Property<string>("ReadModel")
                        .HasColumnType("jsonb")
                        .HasColumnName("read_model");

                    b.Property<string>("SellerName")
                        .HasColumnType("text")
                        .HasColumnName("seller_name");

                    b.Property<string>("SellerVatId")
                        .HasColumnType("text")
                        .HasColumnName("seller_vat_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal?>("TotalGross")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_gross");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<string>("ValidationReport")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation_report");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer")
                        .HasColumnName("validation_status");

                    b.HasKey("Id")
                        .HasName("pk_inbound_document");

                    b.HasIndex("TenantId", "UploadedAt")
                        .HasDatabaseName("ix_inbound_document_tenant_id_uploaded_at");

                    b.ToTable("inbound_document");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Email.DocumentEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_address");

                    b.HasKey("Id")
                        .HasName("pk_document_email");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_document_email_tenant_id_document_id");

                    b.ToTable("document_email");
                });

            modelBuilder.Entity("Numera.Modules.Sales.NumberSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DocType")
                        .HasColumnType("integer")
                        .HasColumnName("doc_type");

                    b.Property<long>("NextValue")
                        .HasColumnType("bigint")
                        .HasColumnName("next_value");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_number_sequences");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_number_sequences_tenant_id_id");

                    b.ToTable("number_sequences");
                });

            modelBuilder.Entity("Numera.Modules.Sales.OpenItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<decimal>("OpenAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("open_amount");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("original_amount");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<decimal?>("SkontoAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("skonto_amount");

                    b.Property<int?>("SkontoDays")
                        .HasColumnType("integer")
                        .HasColumnName("skonto_days");

                    b.Property<DateOnly?>("SkontoDueDate")
                        .HasColumnType("date")
                        .HasColumnName("skonto_due_date");

                    b.Property<decimal?>("SkontoPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("skonto_percent");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_open_items");

                    b.HasIndex("TenantId", "Status", "DueDate")
                        .HasDatabaseName("ix_open_items_tenant_id_status_due_date");

                    b.ToTable("open_items");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Payments.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Reference")
                        .HasColumnType("text")
                        .HasColumnName("reference");

                    b.Property<Guid?>("ReversesPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("reverses_payment_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateOnly>("ValueDate")
                        .HasColumnType("date")
                        .HasColumnName("value_date");

                    b.HasKey("Id")
                        .HasName("pk_payment");

                    b.HasIndex("TenantId", "ValueDate")
                        .HasDatabaseName("ix_payment_tenant_id_value_date");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Payments.PaymentAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocatedAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("allocated_amount");

                    b.Property<Guid>("OpenItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("open_item_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_payment_allocation");

                    b.HasIndex("TenantId", "OpenItemId")
                        .HasDatabaseName("ix_payment_allocation_tenant_id_open_item_id");

                    b.ToTable("payment_allocation");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Recurring.RecurringInvoiceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoFinalize")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_finalize");

                    b.Property<bool>("AutoSend")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_send");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("EndMode")
                        .HasColumnType("integer")
                        .HasColumnName("end_mode");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<DateOnly?>("ExchangeRateDate")
                        .HasColumnType("date")
                        .HasColumnName("exchange_rate_date");

                    b.Property<int>("GeneratedCount")
                        .HasColumnType("integer")
                        .HasColumnName("generated_count");

                    b.Property<int>("IntervalCount")
                        .HasColumnType("integer")
                        .HasColumnName("interval_count");

                    b.Property<int>("IntervalUnit")
                        .HasColumnType("integer")
                        .HasColumnName("interval_unit");

                    b.Property<DateOnly?>("LastGeneratedPeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("last_generated_period_end");

                    b.Property<int?>("MaxOccurrences")
                        .HasColumnType("integer")
                        .HasColumnName("max_occurrences");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateOnly>("NextRunOn")
                        .HasColumnType("date")
                        .HasColumnName("next_run_on");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<DateOnly>("StartOn")
                        .HasColumnType("date")
                        .HasColumnName("start_on");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_invoice_templates");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_recurring_invoice_templates_tenant_id_status");

                    b.ToTable("recurring_invoice_templates");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Recurring.RecurringInvoiceTemplateLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("NetUnitPrice")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("net_unit_price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("quantity");

                    b.Property<int>("TaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("tax_category");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<decimal>("VatRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.HasKey("Id")
                        .HasName("pk_recurring_invoice_template_lines");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("ix_recurring_invoice_template_lines_template_id");

                    b.HasIndex("TenantId", "TemplateId")
                        .HasDatabaseName("ix_recurring_invoice_template_lines_tenant_id_template_id");

                    b.ToTable("recurring_invoice_template_lines");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Rendering.DocumentRender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<byte[]>("PdfBytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pdf_bytes");

                    b.Property<DateTimeOffset>("RenderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("rendered_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_document_render");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_document_render_tenant_id_document_id");

                    b.ToTable("document_render");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountDue")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount_due");

                    b.Property<string>("BuyerReference")
                        .HasColumnType("text")
                        .HasColumnName("buyer_reference");

                    b.Property<Guid?>("CancelledByDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by_document_id");

                    b.Property<Guid?>("CorrectsDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("corrects_document_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<int>("DocumentType")
                        .HasColumnType("integer")
                        .HasColumnName("document_type");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("exchange_rate");

                    b.Property<DateOnly?>("ExchangeRateDate")
                        .HasColumnType("date")
                        .HasColumnName("exchange_rate_date");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<bool>("IsKleinunternehmer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_kleinunternehmer");

                    b.Property<string>("IssuerSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("issuer_snapshot");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("RecipientSnapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("recipient_snapshot");

                    b.Property<string>("RecurringPeriodKey")
                        .HasColumnType("text")
                        .HasColumnName("recurring_period_key");

                    b.Property<Guid?>("RecurringTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurring_template_id");

                    b.Property<bool>("ReverseCharge")
                        .HasColumnType("boolean")
                        .HasColumnName("reverse_charge");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<DateOnly?>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<DateOnly?>("ServicePeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("service_period_end");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_document_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalGross")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_gross");

                    b.Property<decimal>("TotalNet")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_net");

                    b.Property<decimal>("TotalTax")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_tax");

                    b.Property<decimal?>("TotalTaxEur")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("total_tax_eur");

                    b.HasKey("Id")
                        .HasName("pk_sales_documents");

                    b.HasIndex("TenantId", "DocumentType", "Status")
                        .HasDatabaseName("ix_sales_documents_tenant_id_document_type_status");

                    b.HasIndex("TenantId", "RecurringTemplateId", "RecurringPeriodKey")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_documents_tenant_id_recurring_template_id_recurring_p~");

                    b.ToTable("sales_documents");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocumentLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CatalogItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("catalog_item_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal>("LineNetAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("line_net_amount");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer")
                        .HasColumnName("line_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("NetUnitPrice")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("net_unit_price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("numeric(19,6)")
                        .HasColumnName("quantity");

                    b.Property<int>("TaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("tax_category");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unit_code");

                    b.Property<decimal>("VatRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.HasKey("Id")
                        .HasName("pk_sales_document_lines");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_sales_document_lines_document_id");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_sales_document_lines_tenant_id_document_id");

                    b.ToTable("sales_document_lines");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocumentPrepayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("AbschlagDate")
                        .HasColumnType("date")
                        .HasColumnName("abschlag_date");

                    b.Property<Guid>("AbschlagDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("abschlag_document_id");

                    b.Property<string>("AbschlagNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abschlag_number");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("net_amount");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("VatAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("vat_amount");

                    b.HasKey("Id")
                        .HasName("pk_sales_document_prepayment");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_sales_document_prepayment_document_id");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_sales_document_prepayment_tenant_id_document_id");

                    b.ToTable("sales_document_prepayment");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocumentTaxBreakdown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ExemptionReasonCode")
                        .HasColumnType("text")
                        .HasColumnName("exemption_reason_code");

                    b.Property<string>("ExemptionReasonText")
                        .HasColumnType("text")
                        .HasColumnName("exemption_reason_text");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("tax_amount");

                    b.Property<int>("TaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("tax_category");

                    b.Property<decimal>("TaxableBase")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("taxable_base");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("VatRatePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("vat_rate_percent");

                    b.HasKey("Id")
                        .HasName("pk_sales_document_tax_breakdown");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_sales_document_tax_breakdown_document_id");

                    b.HasIndex("TenantId", "DocumentId")
                        .HasDatabaseName("ix_sales_document_tax_breakdown_tenant_id_document_id");

                    b.ToTable("sales_document_tax_breakdown");
                });

            modelBuilder.Entity("Numera.Platform.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<byte[]>("PrevHash")
                        .HasColumnType("bytea")
                        .HasColumnName("prev_hash");

                    b.Property<byte[]>("RowHash")
                        .HasColumnType("bytea")
                        .HasColumnName("row_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_audit_events_tenant_id_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_tenant_id_occurred_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_membership");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_tenant_id_user_id");

                    b.ToTable("membership", (string)null);
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Numera.Modules.Crm.BusinessPartner", b =>
                {
                    b.OwnsOne("Numera.Modules.Crm.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("BusinessPartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_country_code");

                            b1.Property<string>("Line2")
                                .HasColumnType("text")
                                .HasColumnName("billing_address_line2");

                            b1.Property<string>("PoBox")
                                .HasColumnType("text")
                                .HasColumnName("billing_address_po_box");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_street");

                            b1.HasKey("BusinessPartnerId")
                                .HasName("pk_partners");

                            b1.ToTable("partners");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerId")
                                .HasConstraintName("fk_partners_partners__business_partner_id");
                        });

                    b.OwnsOne("Numera.Modules.Crm.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("BusinessPartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_country_code");

                            b1.Property<string>("Line2")
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_line2");

                            b1.Property<string>("PoBox")
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_po_box");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_street");

                            b1.HasKey("BusinessPartnerId")
                                .HasName("pk_partners");

                            b1.ToTable("partners");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerId")
                                .HasConstraintName("fk_partners_partners__business_partner_id");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Numera.Modules.Ledger.Posting", b =>
                {
                    b.HasOne("Numera.Modules.Ledger.JournalEntry", null)
                        .WithMany("Postings")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_postings_journal_entries_journal_entry_id");
                });

            modelBuilder.Entity("Numera.Modules.Sales.CompanyProfile", b =>
                {
                    b.OwnsOne("Numera.Modules.Sales.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CompanyProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_country_code");

                            b1.Property<string>("Line2")
                                .HasColumnType("text")
                                .HasColumnName("address_line2");

                            b1.Property<string>("PoBox")
                                .HasColumnType("text")
                                .HasColumnName("address_po_box");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.HasKey("CompanyProfileId")
                                .HasName("pk_company_profile");

                            b1.ToTable("company_profile");

                            b1.WithOwner()
                                .HasForeignKey("CompanyProfileId")
                                .HasConstraintName("fk_company_profile_company_profile__company_profile_id");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Numera.Modules.Sales.Recurring.RecurringInvoiceTemplateLine", b =>
                {
                    b.HasOne("Numera.Modules.Sales.Recurring.RecurringInvoiceTemplate", null)
                        .WithMany("Lines")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_invoice_template_lines_recurring_invoice_template~");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocumentLine", b =>
                {
                    b.HasOne("Numera.Modules.Sales.SalesDocument", null)
                        .WithMany("Lines")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_document_lines_sales_documents_document_id");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocumentPrepayment", b =>
                {
                    b.HasOne("Numera.Modules.Sales.SalesDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_document_prepayment_sales_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocumentTaxBreakdown", b =>
                {
                    b.HasOne("Numera.Modules.Sales.SalesDocument", null)
                        .WithMany("TaxBreakdown")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sales_document_tax_breakdown_sales_documents_document_id");
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Membership", b =>
                {
                    b.HasOne("Numera.Platform.Db.Entities.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membership_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Numera.Modules.Ledger.JournalEntry", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("Numera.Modules.Sales.Recurring.RecurringInvoiceTemplate", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Numera.Modules.Sales.SalesDocument", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("TaxBreakdown");
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Tenant", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
