// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Numera.Platform.Db;

#nullable disable

namespace Numera.Platform.Db.Migrations
{
    [DbContext(typeof(NumeraDbContext))]
    [Migration("20260711022645_Crm")]
    partial class Crm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Numera.Modules.Crm.BusinessPartner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("Bic")
                        .HasColumnType("text")
                        .HasColumnName("bic");

                    b.Property<string>("CreditorAccount")
                        .HasColumnType("text")
                        .HasColumnName("creditor_account");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("text")
                        .HasColumnName("customer_number");

                    b.Property<string>("DebtorAccount")
                        .HasColumnType("text")
                        .HasColumnName("debtor_account");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("default_currency");

                    b.Property<int?>("DefaultTaxCategory")
                        .HasColumnType("integer")
                        .HasColumnName("default_tax_category");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Iban")
                        .HasColumnType("text")
                        .HasColumnName("iban");

                    b.Property<bool>("IsCustomer")
                        .HasColumnType("boolean")
                        .HasColumnName("is_customer");

                    b.Property<bool>("IsSupplier")
                        .HasColumnType("boolean")
                        .HasColumnName("is_supplier");

                    b.Property<int>("Language")
                        .HasColumnType("integer")
                        .HasColumnName("language");

                    b.Property<string>("LegalForm")
                        .HasColumnType("text")
                        .HasColumnName("legal_form");

                    b.Property<string>("LeitwegId")
                        .HasColumnType("text")
                        .HasColumnName("leitweg_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PaymentTermsNetDays")
                        .HasColumnType("integer")
                        .HasColumnName("payment_terms_net_days");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<int?>("SkontoDays")
                        .HasColumnType("integer")
                        .HasColumnName("skonto_days");

                    b.Property<decimal?>("SkontoPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("skonto_percent");

                    b.Property<string>("SupplierNumber")
                        .HasColumnType("text")
                        .HasColumnName("supplier_number");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text")
                        .HasColumnName("tax_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VatId")
                        .HasColumnType("text")
                        .HasColumnName("vat_id");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_partners");

                    b.HasIndex("TenantId", "Name")
                        .HasDatabaseName("ix_partners_tenant_id_name");

                    b.ToTable("partners");
                });

            modelBuilder.Entity("Numera.Modules.Crm.PartnerActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<Guid?>("RefId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_id");

                    b.Property<string>("RefType")
                        .HasColumnType("text")
                        .HasColumnName("ref_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_partner_activities");

                    b.HasIndex("TenantId", "PartnerId", "OccurredAt")
                        .HasDatabaseName("ix_partner_activities_tenant_id_partner_id_occurred_at");

                    b.ToTable("partner_activities");
                });

            modelBuilder.Entity("Numera.Modules.Crm.PartnerContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Position")
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<string>("Salutation")
                        .HasColumnType("text")
                        .HasColumnName("salutation");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_partner_contacts");

                    b.HasIndex("TenantId", "PartnerId")
                        .HasDatabaseName("ix_partner_contacts_tenant_id_partner_id");

                    b.ToTable("partner_contacts");
                });

            modelBuilder.Entity("Numera.Modules.Crm.PartnerNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("partner_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_partner_notes");

                    b.HasIndex("TenantId", "PartnerId")
                        .HasDatabaseName("ix_partner_notes_tenant_id_partner_id");

                    b.ToTable("partner_notes");
                });

            modelBuilder.Entity("Numera.Modules.Ledger.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_accounts_tenant_id_id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Numera.Modules.Ledger.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<string>("SourceRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_ref");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_journal_entries_tenant_id_id");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Numera.Modules.Ledger.Posting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<Guid>("JournalEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("journal_entry_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_postings");

                    b.HasIndex("JournalEntryId")
                        .HasDatabaseName("ix_postings_journal_entry_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_postings_tenant_id_id");

                    b.ToTable("postings", (string)null);
                });

            modelBuilder.Entity("Numera.Platform.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("After")
                        .HasColumnType("jsonb")
                        .HasColumnName("after");

                    b.Property<string>("Before")
                        .HasColumnType("jsonb")
                        .HasColumnName("before");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<byte[]>("PrevHash")
                        .HasColumnType("bytea")
                        .HasColumnName("prev_hash");

                    b.Property<byte[]>("RowHash")
                        .HasColumnType("bytea")
                        .HasColumnName("row_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_audit_events_tenant_id_id");

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_tenant_id_occurred_at");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_membership");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_membership_tenant_id_user_id");

                    b.ToTable("membership", (string)null);
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Numera.Modules.Crm.BusinessPartner", b =>
                {
                    b.OwnsOne("Numera.Modules.Crm.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("BusinessPartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_country_code");

                            b1.Property<string>("Line2")
                                .HasColumnType("text")
                                .HasColumnName("billing_address_line2");

                            b1.Property<string>("PoBox")
                                .HasColumnType("text")
                                .HasColumnName("billing_address_po_box");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_street");

                            b1.HasKey("BusinessPartnerId")
                                .HasName("pk_partners");

                            b1.ToTable("partners");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerId")
                                .HasConstraintName("fk_partners_partners__business_partner_id");
                        });

                    b.OwnsOne("Numera.Modules.Crm.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("BusinessPartnerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_country_code");

                            b1.Property<string>("Line2")
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_line2");

                            b1.Property<string>("PoBox")
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_po_box");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shipping_address_street");

                            b1.HasKey("BusinessPartnerId")
                                .HasName("pk_partners");

                            b1.ToTable("partners");

                            b1.WithOwner()
                                .HasForeignKey("BusinessPartnerId")
                                .HasConstraintName("fk_partners_partners__business_partner_id");
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Numera.Modules.Ledger.Posting", b =>
                {
                    b.HasOne("Numera.Modules.Ledger.JournalEntry", null)
                        .WithMany("Postings")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_postings_journal_entries_journal_entry_id");
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Membership", b =>
                {
                    b.HasOne("Numera.Platform.Db.Entities.Tenant", "Tenant")
                        .WithMany("Memberships")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_membership_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Numera.Modules.Ledger.JournalEntry", b =>
                {
                    b.Navigation("Postings");
                });

            modelBuilder.Entity("Numera.Platform.Db.Entities.Tenant", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
