<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Numera.Platform.Db</RootNamespace>
    <AssemblyName>Numera.Platform.Db</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Numera.Platform.Tenancy\Numera.Platform.Tenancy.csproj" />
  </ItemGroup>

</Project>
